# Site settings
title: My Portfolio
description: Portfolio selection of my most recent works
# baseurl: "/portfolio" # the subpath of your site, e.g. /blog
# url: "https://rubenbolivar.github.io/portfolio/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ruben Bolivar
user_description: Wordpress designer and developer from ancient times
user_title: Wordpress Developer and Designer
email: rubenbe9@gmail.com
twitter_username: RubenBolivar
github_username:  rubenbolivar
gplus_username:  +RubenBolivar

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
